# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_date_from',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_date_to',
            field=models.CharField(max_length=10),
        ),
    ]
